INSERT INTO USERS VALUES (1, 'user1', 'user1', 'admin', 'user1@user.com', 'password', 1);
INSERT INTO USERS VALUES (2, 'user2', 'user2', 'user-manager', 'user2@user.com', 'password', 1);
INSERT INTO USERS VALUES (3, 'user3', 'user3', 'role-manager', 'user3@user.com', 'password', 1);
INSERT INTO USERS VALUES (4, 'user4', 'user4', 'perm-groups-manager', 'user4@user.com', 'password', 1);
INSERT INTO USERS VALUES (5, 'user5', 'user5', 'content_manager', 'user4@user.com', 'password', 1);
INSERT INTO USERS VALUES (6, 'user6', 'user5', 'user', 'user4@user.com', 'password', 1);
INSERT INTO USERS VALUES (7, 'user6', 'user5', 'user-for-deletion', 'user4@user.com', 'password', 1);

INSERT INTO PERMISSION_GROUPS VALUES (1, 'permission-group-admin');
INSERT INTO PERMISSION_GROUPS VALUES (2, 'permission-group-role-manager');
INSERT INTO PERMISSION_GROUPS VALUES (3, 'permission-group-content-manage');
INSERT INTO PERMISSION_GROUPS VALUES (4, 'permission-group-moderation-manage');
INSERT INTO PERMISSION_GROUPS VALUES (5, 'permission-group-manage');
INSERT INTO PERMISSION_GROUPS VALUES (6, 'permission-group-user');
INSERT INTO PERMISSION_GROUPS VALUES (7, 'permission-group-user');

INSERT INTO CONTENT VALUES (1, 'mkyong', 'mkyong');
INSERT INTO CONTENT VALUES (2, 'alex', 'alex');
INSERT INTO CONTENT VALUES (3, 'joel', 'joel');

INSERT INTO ROLES VALUES (1, 'ROLE_ADMIN');
INSERT INTO ROLES VALUES (2, 'ROLE_USER_MANAGER');
INSERT INTO ROLES VALUES (3, 'ROLE_ROLE_MANAGER');
INSERT INTO ROLES VALUES (4, 'ROLE_PERMGROUPS_MANAGER');
INSERT INTO ROLES VALUES (5, 'ROLE_CONTENT_MANAGER');
INSERT INTO ROLES VALUES (6, 'ROLE_USER');

INSERT INTO PERMISSIONS VALUES (1, 'create-user');
INSERT INTO PERMISSIONS VALUES (2, 'read-user');
INSERT INTO PERMISSIONS VALUES (3, 'update-user');
INSERT INTO PERMISSIONS VALUES (4, 'delete-user');
INSERT INTO PERMISSIONS VALUES (5, 'read-all-users');
INSERT INTO PERMISSIONS VALUES (6, 'link-user-with-roles');
INSERT INTO PERMISSIONS VALUES (7, 'read-exist-roles-of-user');
INSERT INTO PERMISSIONS VALUES (8, 'unlink-user-with-roles');
INSERT INTO PERMISSIONS VALUES (9, 'link-user-with-separate-permissions');
INSERT INTO PERMISSIONS VALUES (10, 'read-exist-separate-permissions-of-user');
INSERT INTO PERMISSIONS VALUES (11, 'unlink-user-with-separate-permissions');

INSERT INTO PERMISSIONS VALUES (12, 'create-role');
INSERT INTO PERMISSIONS VALUES (13, 'read-role');
INSERT INTO PERMISSIONS VALUES (14, 'update-role');
INSERT INTO PERMISSIONS VALUES (15, 'delete-role');
INSERT INTO PERMISSIONS VALUES (16, 'read-all-roles');
INSERT INTO PERMISSIONS VALUES (17, 'link-role-with-permission-groups');
INSERT INTO PERMISSIONS VALUES (18, 'read-exist-permission-groups-of-role');
INSERT INTO PERMISSIONS VALUES (19, 'unlink-role-with-permission-groups');

INSERT INTO PERMISSIONS VALUES (20, 'create-permission-group');
INSERT INTO PERMISSIONS VALUES (21, 'read-permission-group');
INSERT INTO PERMISSIONS VALUES (22, 'update-permission-group');
INSERT INTO PERMISSIONS VALUES (23, 'delete-permission-group');
INSERT INTO PERMISSIONS VALUES (24, 'read-all-permission-groups');
INSERT INTO PERMISSIONS VALUES (25, 'link-permission-group-with-permissions');
INSERT INTO PERMISSIONS VALUES (26, 'read-exist-permissions-of-permission-group');
INSERT INTO PERMISSIONS VALUES (27, 'unlink-permission-group-with-permissions');

INSERT INTO PERMISSIONS VALUES (28, 'create-permission');
INSERT INTO PERMISSIONS VALUES (29, 'read-permission');
INSERT INTO PERMISSIONS VALUES (30, 'update-permission');
INSERT INTO PERMISSIONS VALUES (31, 'delete-permission');
INSERT INTO PERMISSIONS VALUES (32, 'read-all-permissions');

INSERT INTO PERMISSIONS VALUES (33, 'create-content');
INSERT INTO PERMISSIONS VALUES (34, 'read-content');
INSERT INTO PERMISSIONS VALUES (35, 'update-content');
INSERT INTO PERMISSIONS VALUES (36, 'delete-content');

INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (1, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (2, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (3, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (4, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (5, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (6, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (7, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (8, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (9, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (10, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (11, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (12, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (13, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (14, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (15, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (16, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (17, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (18, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (19, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (20, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (21, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (22, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (23, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (24, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (25, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (26, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (27, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (28, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (29, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (30, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (31, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (32, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (33, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (34, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (35, 1);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (36, 1);

INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (1, 2);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (2, 2);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (3, 2);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (4, 2);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (5, 2);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (6, 2);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (7, 2);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (8, 2);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (9, 2);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (10, 2);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (11, 2);

INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (12, 3);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (13, 3);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (14, 3);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (15, 3);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (16, 3);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (17, 3);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (18, 3);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (19, 3);

INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (20, 4);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (21, 4);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (22, 4);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (23, 4);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (24, 4);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (25, 4);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (26, 4);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (27, 4);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (28, 4);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (29, 4);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (30, 4);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (31, 4);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (32, 4);

INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (33, 5);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (34, 5);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (35, 5);
INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (36, 5);

INSERT INTO PERMISSIONS_PERMISSION_GROUPS VALUES (34, 6);


INSERT INTO ROLES_PERMISSION_GROUPS VALUES (1, 1);
INSERT INTO ROLES_PERMISSION_GROUPS VALUES (1, 2);
INSERT INTO ROLES_PERMISSION_GROUPS VALUES (1, 3);
INSERT INTO ROLES_PERMISSION_GROUPS VALUES (1, 4);
INSERT INTO ROLES_PERMISSION_GROUPS VALUES (1, 5);
INSERT INTO ROLES_PERMISSION_GROUPS VALUES (2, 2);
INSERT INTO ROLES_PERMISSION_GROUPS VALUES (3, 3);
INSERT INTO ROLES_PERMISSION_GROUPS VALUES (4, 4);
INSERT INTO ROLES_PERMISSION_GROUPS VALUES (5, 5);
INSERT INTO ROLES_PERMISSION_GROUPS VALUES (6, 6);


INSERT INTO USERS_ROLES VALUES (1, 1);
INSERT INTO USERS_ROLES VALUES (1, 2);
INSERT INTO USERS_ROLES VALUES (1, 3);
INSERT INTO USERS_ROLES VALUES (1, 4);
INSERT INTO USERS_ROLES VALUES (1, 5);
INSERT INTO USERS_ROLES VALUES (2, 2);
INSERT INTO USERS_ROLES VALUES (3, 3);
INSERT INTO USERS_ROLES VALUES (4, 4);
INSERT INTO USERS_ROLES VALUES (5, 5);
INSERT INTO USERS_ROLES VALUES (6, 6);

INSERT INTO USERS_PERMISSIONS VALUES (1, 1);
INSERT INTO USERS_PERMISSIONS VALUES (1, 2);
INSERT INTO USERS_PERMISSIONS VALUES (1, 3);
INSERT INTO USERS_PERMISSIONS VALUES (2, 1);
INSERT INTO USERS_PERMISSIONS VALUES (2, 2);


