CREATE TABLE CONTENT (
  CONTENT_ID NUMERIC auto_increment primary key,
  CONTENT_TITLE VARCHAR(30),
  CONTENT_TEXT VARCHAR(300)
);

CREATE TABLE PERMISSIONS (
  PERMISSION_ID NUMERIC auto_increment primary key,
  PERMISSION_NAME VARCHAR(50)
);

CREATE TABLE USERS (
  USER_ID NUMERIC auto_increment primary key,
  FIRST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  USER_NAME VARCHAR(50),
  USER_EMAIL VARCHAR(50)
);

CREATE TABLE PERMISSION_GROUPS (
  PERMISSION_GROUP_ID NUMERIC auto_increment primary key,
  PERMISSION_GROUP_NAME VARCHAR(50)
);

CREATE TABLE ROLES (
  ROLE_ID NUMERIC auto_increment primary key,
  ROLE_NAME VARCHAR(30)
);

CREATE TABLE PERMISSIONS_PERMISSION_GROUPS (
  PERMISSION_ID NUMERIC,
  PERMISSION_GROUP_ID NUMERIC
);
ALTER TABLE PERMISSIONS_PERMISSION_GROUPS ADD FOREIGN KEY ( PERMISSION_ID ) REFERENCES PERMISSIONS( PERMISSION_ID ) ;
ALTER TABLE PERMISSIONS_PERMISSION_GROUPS ADD FOREIGN KEY ( PERMISSION_GROUP_ID ) REFERENCES PERMISSION_GROUPS( PERMISSION_GROUP_ID ) ;

CREATE TABLE ROLES_PERMISSION_GROUPS (
  ROLE_ID NUMERIC,
  PERMISSION_GROUP_ID NUMERIC
);
ALTER TABLE ROLES_PERMISSION_GROUPS ADD FOREIGN KEY ( ROLE_ID ) REFERENCES ROLES( ROLE_ID ) ;
ALTER TABLE ROLES_PERMISSION_GROUPS ADD FOREIGN KEY ( PERMISSION_GROUP_ID ) REFERENCES PERMISSION_GROUPS( PERMISSION_GROUP_ID ) ;

CREATE TABLE USERS_ROLES (
  USER_ID NUMERIC,
  ROLE_ID NUMERIC
);
ALTER TABLE USERS_ROLES ADD FOREIGN KEY ( USER_ID ) REFERENCES USERS( USER_ID ) ;
ALTER TABLE USERS_ROLES ADD FOREIGN KEY ( ROLE_ID ) REFERENCES ROLES( ROLE_ID ) ;
